In [1]:
import argparse
from collections import Counter
import pickle
import random
import json
import sys
import numpy as np
import dynet as dy # Loaded late to avoid memory allocation when we just want help info
import re

In [2]:
## Command line argument handling and default configuration ##

abstract_lang = 'sql'
###abstract_lang = 'logic'
sys.argv = ['baseline_model','../data/atis.json','--do_test_eval']
#--eval_freq 1000000 --log_freq 1000000 --max_bad_iters -1 --do_test_eval

In [3]:
parser = argparse.ArgumentParser(description='A simple template-based text-to-SQL system.')

# IO
parser.add_argument('data', help='Data in json format', nargs='+')
parser.add_argument('--unk_max', help='Maximum count to be considered an unknown word', type=int, default=0)
parser.add_argument('--query_split', help='Use the query split rather than the question split', action='store_true')
parser.add_argument('--no_vars', help='Run without filling in variables', action='store_true')
parser.add_argument('--use_all_sql', help='Default is to use first SQL only, this makes multiple instances.', action='store_true')
parser.add_argument('--do_test_eval', help='Do the final evaluation on the test set (rather than dev).', action='store_true')
parser.add_argument('--split', help='Use this split in cross-validation.', type=int)

# Model
parser.add_argument('--mlp', help='Use a multi-layer perceptron', action='store_true')
parser.add_argument('--dim_word', help='Dimensionality of word embeddings', type=int, default=128)
parser.add_argument('--dim_hidden_lstm', help='Dimensionality of LSTM hidden vectors', type=int, default=64)
parser.add_argument('--dim_hidden_mlp', help='Dimensionality of MLP hidden vectors', type=int, default=32)
parser.add_argument('--dim_hidden_template', help='Dimensionality of MLP hidden vectors for the final template choice', type=int, default=64)
parser.add_argument('--word_vectors', help='Pre-built word embeddings')
parser.add_argument('--lstm_layers', help='Number of layers in the LSTM', type=int, default=2)

# Training
parser.add_argument('--max_iters', help='Maximum number of training iterations', type=int, default=40)
parser.add_argument('--max_bad_iters', help='Maximum number of consecutive training iterations without improvement', type=int, default=1)
parser.add_argument('--log_freq', help='Number of examples to decode between logging', type=int, default=1000000)
parser.add_argument('--eval_freq', help='Number of examples to decode between evaluation runs', type=int, default=500000)
parser.add_argument('--train_noise', help='Noise added to word embeddings as regularization', type=float, default=0.1)
parser.add_argument('--lstm_dropout', help='Dropout for input and hidden elements of the LSTM', type=float, default=0.0)
parser.add_argument('--learning_rate', help='Learning rate for optimiser', type=float, default="0.1")

args = parser.parse_args()

In [4]:
## Input ##

def insert_variables(sql, sql_variables, sent, sent_variables):
    tokens = []
    tags = []
    for token in sent.strip().split():
        if (token not in sent_variables) or args.no_vars:
            tokens.append(token)
            tags.append("O")
        else:
            assert len(sent_variables[token]) > 0
            for word in sent_variables[token].split():
                tokens.append(word)
                tags.append(token)

    sql_tokens = []
    for token in sql.strip().split():
        if token.startswith('"%') or token.startswith("'%"):
            sql_tokens.append(token[:2])
            token = token[2:]
        elif token.startswith('"') or token.startswith("'"):
            sql_tokens.append(token[0])
            token = token[1:]

        if token.endswith('%"') or token.endswith("%'"):
            sql_tokens.append(token[:-2])
            sql_tokens.append(token[-2:])
        elif token.endswith('"') or token.endswith("'"):
            sql_tokens.append(token[:-1])
            sql_tokens.append(token[-1])
        else:
            sql_tokens.append(token)

    template = []
    for token in sql_tokens:
        if (token not in sent_variables) and (token not in sql_variables):
            template.append(token)
        elif token in sent_variables:
            if sent_variables[token] == '':
                example = None
                for variable in sql_variables:
                    if variable['name'] == token:
                        example = variable['example']
                assert example is not None
                template.append(example)
            else:
                #template.append(token)
                template.append(sent_variables[token])
        elif token in sql_variables:
            example = None
            for variable in sql_variables:
                if variable['name'] == token:
                    example = variable['example']
            assert example is not None
            template.append(example)
            
    return (tokens, tags, ' '.join(template) )



def get_tagged_data_for_query(data):
    dataset = data['query-split']
    for sent_info in data['sentences']:
        if not args.query_split:
            dataset = sent_info['question-split']

        if args.split is not None:
            if str(args.split) == str(dataset):
                dataset = "test"
            else:
                dataset = "train"

        for sql in data[abstract_lang]:
            sql_vars = data['variables']
            text = sent_info['text']
            text_vars = sent_info['variables']

            yield (dataset, insert_variables(sql, sql_vars, text, text_vars))

            if not args.use_all_sql:
                break

In [5]:
train = []
dev = []
test = []
for filename in args.data:
    with open(filename) as input_file:
        data = json.load(input_file)
        if type(data) == list:
            for example in data:
                for dataset, instance in get_tagged_data_for_query(example):
                    if dataset == 'train':
                        train.append(instance)
                    elif dataset == 'dev':
                        if args.do_test_eval:
                            train.append(instance)
                        else:
                            dev.append(instance)
                    elif dataset == 'test':
                        test.append(instance)
                    elif dataset == 'exclude':
                        pass
                    else:
                        assert False, dataset
        else:
            for dataset, instance in get_tagged_data_for_query(data):
                if dataset == 'train':
                    train.append(instance)
                elif dataset == 'dev':
                    if args.do_test_eval:
                        train.append(instance)
                    else:
                        dev.append(instance)
                elif dataset == 'test':
                    test.append(instance)
                elif dataset == 'exclude':
                    pass
                else:
                    assert False, dataset

In [6]:
!pip install termcolor

Requirement already satisfied (use --upgrade to upgrade): termcolor in /opt/conda/lib/python3.5/site-packages
You are using pip version 8.1.2, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [7]:
from termcolor import colored
from random import randint

In [8]:
count = 100
l = len(train)
print(l)
# for i in range(count):
#     print()
#     print( colored(' '.join(train[ind][0]), "red"))
#     print(train[ind][2])

4833

In [9]:
train_orig = list(train)
#train = train

In [50]:
def is_nested(sql):
    select_count = sql.count('SELECT')
    return (select_count > 1)

def is_or(sql):
    or_count = sql.count(' OR ')
    return (or_count > 0)

def is_in(sql):
    in_count = sql.count(' IN ')
    return (in_count > 0)

def is_by(sql):
    in_count = sql.count(' BY ')
    return (in_count > 0)

def is_like(sql):
    like_count = sql.count(' LIKE ')
    return (like_count > 0)

In [10]:
train = [ex for ex in train if ex[2].count('SELECT') == 1]
print(len(train))
train = [ex for ex in train if ex[2].count(' OR ') == 0]
print(len(train))
train = [ex for ex in train if ex[2].count(' IN ') == 0]
print(len(train))
train = [ex for ex in train if ex[2].count(' BY ') == 0]
print(len(train))
train = [ex for ex in train if ex[2].count(' LIKE ') == 0]
print(len(train))
train = [ex for ex in train if ex[2].count(' JOIN ') == 0]
print(len(train))
train = [ex for ex in train if ex[2].count(' BETWEEN ') == 0]
print(len(train))
train = [ex for ex in train if ex[2].count('alias1') == 0]
print(len(train))

4226
4008
4008
3999
3985
3985
3577
684

In [49]:
print(len(train))

97

In [50]:
def split_list(word_list, delim):
    final_list = []
    for word in word_list:
        final_list += word.split(delim)
    return final_list

In [51]:
train_dataset = []
for example in train:
    sample = {}
    #print(example[0])
    #print(example[2])
    sample["input"] = ' '.join(example[0])
    sample["sql_original"] = example[2]
    sql = re.sub('[;()]','',example[2])
    sql_list = sql.split(' FROM ')
    sql_list = split_list(sql_list, ' WHERE ')
    
    sample["select"] = sql_list[0]
    sample["from"] = sql_list[1]
    
    where_str = ""
    cond_list = []
    cond_join_list = []
    
    if len(sql_list) > 2:
        where_str = sql_list[2]
        where_list = where_str.split(' AND ')
        for cond in where_list:
            words = cond.split()
#             if len(words) != 3:
#                 print(words)
#                 print()
            if 'alias' in words[2]:
                cond_join_list.append(cond)
            else:
                cond_list.append(cond)
    
    sample["cond_list"] = cond_list
    sample["cond_join_list"] = cond_join_list
    train_dataset.append(sample)

#     print(cond_list)
#     print(cond_join_list)

In [52]:
random.shuffle(train_dataset)
for example in train_dataset:
    print(colored(example["input"], "red"))
    print(example["sql_original"])
    print()

what is the seating capacity of a 72S
SELECT DISTINCT AIRCRAFTalias0.AIRCRAFT_CODE FROM AIRCRAFT AS AIRCRAFTalias0 WHERE AIRCRAFTalias0.AIRCRAFT_CODE = " 72S " ;

what does fare code BH mean
SELECT DISTINCT FARE_BASISalias0.FARE_BASIS_CODE FROM FARE_BASIS AS FARE_BASISalias0 WHERE FARE_BASISalias0.FARE_BASIS_CODE = " BH " ;

tell me all the airports near WESTCHESTER COUNTY
SELECT DISTINCT AIRPORTalias0.AIRPORT_CODE FROM AIRPORT AS AIRPORTalias0 , AIRPORT_SERVICE AS AIRPORT_SERVICEalias0 , CITY AS CITYalias0 WHERE AIRPORTalias0.AIRPORT_CODE = AIRPORT_SERVICEalias0.AIRPORT_CODE AND CITYalias0.CITY_CODE = AIRPORT_SERVICEalias0.CITY_CODE AND CITYalias0.CITY_NAME = " WESTCHESTER COUNTY " ;

ground transportation for LAS VEGAS
SELECT DISTINCT GROUND_SERVICEalias0.TRANSPORT_TYPE FROM CITY AS CITYalias0 , GROUND_SERVICE AS GROUND_SERVICEalias0 WHERE CITYalias0.CITY_NAME = " LAS VEGAS " AND GROUND_SERVICEalias0.CITY_CODE = CITYalias0.CITY_CODE ;

how many passengers can fly on a 757
SELECT DISTINCT AIRCRAFTalias0.AIRCRAFT_CODE FROM AIRCRAFT AS AIRCRAFTalias0 WHERE AIRCRAFTalias0.AIRCRAFT_CODE = " 757 " ;

show me a return flight from MIAMI to JFK please
SELECT DISTINCT FLIGHTalias0.FLIGHT_ID FROM AIRPORT AS AIRPORTalias0 , AIRPORT_SERVICE AS AIRPORT_SERVICEalias0 , CITY AS CITYalias0 , FLIGHT AS FLIGHTalias0 WHERE AIRPORTalias0.AIRPORT_CODE = " JFK " AND CITYalias0.CITY_CODE = AIRPORT_SERVICEalias0.CITY_CODE AND CITYalias0.CITY_NAME = " MIAMI " AND FLIGHTalias0.FROM_AIRPORT = AIRPORT_SERVICEalias0.AIRPORT_CODE AND FLIGHTalias0.TO_AIRPORT = AIRPORTalias0.AIRPORT_CODE ;

tell me about the M80 aircraft
SELECT DISTINCT AIRCRAFTalias0.AIRCRAFT_CODE FROM AIRCRAFT AS AIRCRAFTalias0 WHERE AIRCRAFTalias0.AIRCRAFT_CODE = " M80 " ;

which airline is AS
SELECT DISTINCT AIRLINEalias0.AIRLINE_CODE FROM AIRLINE AS AIRLINEalias0 WHERE AIRLINEalias0.AIRLINE_CODE = " AS " ;

what is the seating capacity of the M80
SELECT DISTINCT AIRCRAFTalias0.AIRCRAFT_CODE FROM AIRCRAFT AS AIRCRAFTalias0 WHERE AIRCRAFTalias0.AIRCRAFT_CODE = " M80 " ;

list airports
SELECT DISTINCT AIRPORTalias0.AIRPORT_CODE FROM AIRPORT AS AIRPORTalias0 ;

what does fare code BH mean
SELECT DISTINCT FARE_BASISalias0.FARE_BASIS_CODE FROM FARE_BASIS AS FARE_BASISalias0 WHERE FARE_BASISalias0.FARE_BASIS_CODE = " BH " ;

tell me about the M80 aircraft
SELECT DISTINCT AIRCRAFTalias0.AIRCRAFT_CODE FROM AIRCRAFT AS AIRCRAFTalias0 WHERE AIRCRAFTalias0.AIRCRAFT_CODE = " M80 " ;

list all AS flights
SELECT DISTINCT FLIGHTalias0.FLIGHT_ID FROM FLIGHT AS FLIGHTalias0 WHERE ( FLIGHTalias0.AIRLINE_CODE = " AS " ) ;

what does fare code QO mean
SELECT DISTINCT FARE_BASISalias0.FARE_BASIS_CODE FROM FARE_BASIS AS FARE_BASISalias0 WHERE FARE_BASISalias0.FARE_BASIS_CODE = " QO " ;

what is the capacity of the 73S
SELECT DISTINCT AIRCRAFTalias0.AIRCRAFT_CODE FROM AIRCRAFT AS AIRCRAFTalias0 WHERE AIRCRAFTalias0.AIRCRAFT_CODE = " 73S " ;

what does fare code F mean
SELECT DISTINCT CLASS_OF_SERVICEalias0.BOOKING_CLASS FROM CLASS_OF_SERVICE AS CLASS_OF_SERVICEalias0 WHERE CLASS_OF_SERVICEalias0.BOOKING_CLASS = " F " ;

what the abbreviation US stand for
SELECT DISTINCT AIRLINEalias0.AIRLINE_CODE FROM AIRLINE AS AIRLINEalias0 WHERE AIRLINEalias0.AIRLINE_CODE = " US " ;

what airline is HP
SELECT DISTINCT AIRLINEalias0.AIRLINE_CODE FROM AIRLINE AS AIRLINEalias0 WHERE AIRLINEalias0.AIRLINE_CODE = " HP " ;

what are restrictions AP/57
SELECT DISTINCT RESTRICTIONalias0.ADVANCE_PURCHASE , RESTRICTIONalias0.APPLICATION , RESTRICTIONalias0.MAXIMUM_STAY , RESTRICTIONalias0.MINIMUM_STAY , RESTRICTIONalias0.NO_DISCOUNTS , RESTRICTIONalias0.RESTRICTION_CODE , RESTRICTIONalias0.SATURDAY_STAY_REQUIRED , RESTRICTIONalias0.STOPOVERS FROM RESTRICTION AS RESTRICTIONalias0 WHERE RESTRICTIONalias0.RESTRICTION_CODE = " AP/57 " ;

tell me about the type of aircraft called an M80
SELECT DISTINCT AIRCRAFTalias0.AIRCRAFT_CODE FROM AIRCRAFT AS AIRCRAFTalias0 WHERE AIRCRAFTalias0.AIRCRAFT_CODE = " M80 " ;

what airline is AS
SELECT DISTINCT AIRLINEalias0.AIRLINE_CODE FROM AIRLINE AS AIRLINEalias0 WHERE AIRLINEalias0.AIRLINE_CODE = " AS " ;

what cities does NW fly to
SELECT DISTINCT CITYalias0.CITY_CODE FROM AIRPORT_SERVICE AS AIRPORT_SERVICEalias0 , CITY AS CITYalias0 , FLIGHT AS FLIGHTalias0 WHERE CITYalias0.CITY_CODE = AIRPORT_SERVICEalias0.CITY_CODE AND FLIGHTalias0.AIRLINE_CODE = " NW " AND FLIGHTalias0.FROM_AIRPORT = AIRPORT_SERVICEalias0.AIRPORT_CODE ;

what does fare code Y mean
SELECT DISTINCT FARE_BASISalias0.FARE_BASIS_CODE FROM FARE_BASIS AS FARE_BASISalias0 WHERE FARE_BASISalias0.FARE_BASIS_CODE = " Y " ;

tell me about the ground transportation from NASHVILLE airport
SELECT DISTINCT GROUND_SERVICEalias0.TRANSPORT_TYPE FROM CITY AS CITYalias0 , GROUND_SERVICE AS GROUND_SERVICEalias0 WHERE CITYalias0.CITY_NAME = " NASHVILLE " AND GROUND_SERVICEalias0.CITY_CODE = CITYalias0.CITY_CODE ;

how many NW flights leave ST. PAUL
SELECT COUNT( DISTINCT FLIGHTalias0.FLIGHT_ID ) FROM AIRPORT_SERVICE AS AIRPORT_SERVICEalias0 , CITY AS CITYalias0 , FLIGHT AS FLIGHTalias0 WHERE CITYalias0.CITY_CODE = AIRPORT_SERVICEalias0.CITY_CODE AND CITYalias0.CITY_NAME = " ST. PAUL " AND FLIGHTalias0.AIRLINE_CODE = " NW " AND FLIGHTalias0.FROM_AIRPORT = AIRPORT_SERVICEalias0.AIRPORT_CODE ;

what is a D9S
SELECT DISTINCT AIRCRAFTalias0.AIRCRAFT_CODE FROM AIRCRAFT AS AIRCRAFTalias0 WHERE AIRCRAFTalias0.AIRCRAFT_CODE = " D9S " ;

what is the seating capacity of the aircraft 72S
SELECT DISTINCT AIRCRAFTalias0.AIRCRAFT_CODE FROM AIRCRAFT AS AIRCRAFTalias0 WHERE AIRCRAFTalias0.AIRCRAFT_CODE = " 72S " ;

is there ground transportation available at the PHOENIX airport
SELECT DISTINCT GROUND_SERVICEalias0.TRANSPORT_TYPE FROM CITY AS CITYalias0 , GROUND_SERVICE AS GROUND_SERVICEalias0 WHERE CITYalias0.CITY_NAME = " PHOENIX " AND GROUND_SERVICEalias0.CITY_CODE = CITYalias0.CITY_CODE ;

which airline is US
SELECT DISTINCT AIRLINEalias0.AIRLINE_CODE FROM AIRLINE AS AIRLINEalias0 WHERE AIRLINEalias0.AIRLINE_CODE = " US " ;

list airports
SELECT DISTINCT AIRPORTalias0.AIRPORT_CODE FROM AIRPORT AS AIRPORTalias0 ;

what does fare code H mean
SELECT DISTINCT CLASS_OF_SERVICEalias0.BOOKING_CLASS FROM CLASS_OF_SERVICE AS CLASS_OF_SERVICEalias0 WHERE CLASS_OF_SERVICEalias0.BOOKING_CLASS = " H " ;

what does fare code F mean
SELECT DISTINCT CLASS_OF_SERVICEalias0.BOOKING_CLASS FROM CLASS_OF_SERVICE AS CLASS_OF_SERVICEalias0 WHERE CLASS_OF_SERVICEalias0.BOOKING_CLASS = " F " ;

what airline is HP
SELECT DISTINCT AIRLINEalias0.AIRLINE_CODE FROM AIRLINE AS AIRLINEalias0 WHERE AIRLINEalias0.AIRLINE_CODE = " HP " ;

what airline is YX
SELECT DISTINCT AIRLINEalias0.AIRLINE_CODE FROM AIRLINE AS AIRLINEalias0 WHERE AIRLINEalias0.AIRLINE_CODE = " YX " ;

which airline is KW
SELECT DISTINCT AIRLINEalias0.AIRLINE_CODE FROM AIRLINE AS AIRLINEalias0 WHERE AIRLINEalias0.AIRLINE_CODE = " KW " ;

what is the seating capacity of the 733
SELECT DISTINCT AIRCRAFTalias0.AIRCRAFT_CODE FROM AIRCRAFT AS AIRCRAFTalias0 WHERE AIRCRAFTalias0.AIRCRAFT_CODE = " 733 " ;

which airline is US
SELECT DISTINCT AIRLINEalias0.AIRLINE_CODE FROM AIRLINE AS AIRLINEalias0 WHERE AIRLINEalias0.AIRLINE_CODE = " US " ;

list the cities from which NW flies
SELECT DISTINCT CITYalias0.CITY_CODE FROM AIRPORT_SERVICE AS AIRPORT_SERVICEalias0 , CITY AS CITYalias0 , FLIGHT AS FLIGHTalias0 WHERE CITYalias0.CITY_CODE = AIRPORT_SERVICEalias0.CITY_CODE AND FLIGHTalias0.AIRLINE_CODE = " NW " AND FLIGHTalias0.FROM_AIRPORT = AIRPORT_SERVICEalias0.AIRPORT_CODE ;

list all flights departing from SEATTLE
SELECT DISTINCT FLIGHTalias0.FLIGHT_ID FROM AIRPORT_SERVICE AS AIRPORT_SERVICEalias0 , CITY AS CITYalias0 , FLIGHT AS FLIGHTalias0 WHERE CITYalias0.CITY_CODE = AIRPORT_SERVICEalias0.CITY_CODE AND CITYalias0.CITY_NAME = " SEATTLE " AND FLIGHTalias0.FROM_AIRPORT = AIRPORT_SERVICEalias0.AIRPORT_CODE ;

show me the airports serviced by FF
SELECT DISTINCT AIRPORTalias0.AIRPORT_CODE FROM AIRPORT AS AIRPORTalias0 , FLIGHT AS FLIGHTalias0 WHERE FLIGHTalias0.AIRLINE_CODE = " FF " AND FLIGHTalias0.TO_AIRPORT = AIRPORTalias0.AIRPORT_CODE ;

what is a D9S
SELECT DISTINCT AIRCRAFTalias0.AIRCRAFT_CODE FROM AIRCRAFT AS AIRCRAFTalias0 WHERE AIRCRAFTalias0.AIRCRAFT_CODE = " D9S " ;

what is the seating capacity on the aircraft 733
SELECT DISTINCT AIRCRAFTalias0.AIRCRAFT_CODE FROM AIRCRAFT AS AIRCRAFTalias0 WHERE AIRCRAFTalias0.AIRCRAFT_CODE = " 733 " ;

what airline is HP
SELECT DISTINCT AIRLINEalias0.AIRLINE_CODE FROM AIRLINE AS AIRLINEalias0 WHERE AIRLINEalias0.AIRLINE_CODE = " HP " ;

which airline is US
SELECT DISTINCT AIRLINEalias0.AIRLINE_CODE FROM AIRLINE AS AIRLINEalias0 WHERE AIRLINEalias0.AIRLINE_CODE = " US " ;

list airports in LOS ANGELES
SELECT DISTINCT AIRPORTalias0.AIRPORT_CODE FROM AIRPORT AS AIRPORTalias0 , AIRPORT_SERVICE AS AIRPORT_SERVICEalias0 , CITY AS CITYalias0 WHERE AIRPORTalias0.AIRPORT_CODE = AIRPORT_SERVICEalias0.AIRPORT_CODE AND CITYalias0.CITY_CODE = AIRPORT_SERVICEalias0.CITY_CODE AND CITYalias0.CITY_NAME = " LOS ANGELES " ;

which airline is US
SELECT DISTINCT AIRLINEalias0.AIRLINE_CODE FROM AIRLINE AS AIRLINEalias0 WHERE AIRLINEalias0.AIRLINE_CODE = " US " ;

what ground transportation is there in BALTIMORE
SELECT DISTINCT GROUND_SERVICEalias0.TRANSPORT_TYPE FROM CITY AS CITYalias0 , GROUND_SERVICE AS GROUND_SERVICEalias0 WHERE CITYalias0.CITY_NAME = " BALTIMORE " AND GROUND_SERVICEalias0.CITY_CODE = CITYalias0.CITY_CODE ;

what is TPA
SELECT DISTINCT AIRPORTalias0.AIRPORT_CODE FROM AIRPORT AS AIRPORTalias0 WHERE AIRPORTalias0.AIRPORT_CODE = " TPA " ;

list the airports in LOS ANGELES
SELECT DISTINCT AIRPORTalias0.AIRPORT_CODE FROM AIRPORT AS AIRPORTalias0 , AIRPORT_SERVICE AS AIRPORT_SERVICEalias0 , CITY AS CITYalias0 WHERE AIRPORTalias0.AIRPORT_CODE = AIRPORT_SERVICEalias0.AIRPORT_CODE AND CITYalias0.CITY_CODE = AIRPORT_SERVICEalias0.CITY_CODE AND CITYalias0.CITY_NAME = " LOS ANGELES " ;

is there ground transportation available at the SALT LAKE CITY airport
SELECT DISTINCT GROUND_SERVICEalias0.TRANSPORT_TYPE FROM CITY AS CITYalias0 , GROUND_SERVICE AS GROUND_SERVICEalias0 WHERE CITYalias0.CITY_NAME = " SALT LAKE CITY " AND GROUND_SERVICEalias0.CITY_CODE = CITYalias0.CITY_CODE ;

what does fare code BH mean
SELECT DISTINCT FARE_BASISalias0.FARE_BASIS_CODE FROM FARE_BASIS AS FARE_BASISalias0 WHERE FARE_BASISalias0.FARE_BASIS_CODE = " BH " ;

list airports in LOS ANGELES
SELECT DISTINCT AIRPORTalias0.AIRPORT_CODE FROM AIRPORT AS AIRPORTalias0 , AIRPORT_SERVICE AS AIRPORT_SERVICEalias0 , CITY AS CITYalias0 WHERE AIRPORTalias0.AIRPORT_CODE = AIRPORT_SERVICEalias0.AIRPORT_CODE AND CITYalias0.CITY_CODE = AIRPORT_SERVICEalias0.CITY_CODE AND CITYalias0.CITY_NAME = " LOS ANGELES " ;

what does fare code BH mean
SELECT DISTINCT FARE_BASISalias0.FARE_BASIS_CODE FROM FARE_BASIS AS FARE_BASISalias0 WHERE FARE_BASISalias0.FARE_BASIS_CODE = " BH " ;

show DL flights from JFK to MIAMI
SELECT DISTINCT FLIGHTalias0.FLIGHT_ID FROM AIRPORT AS AIRPORTalias0 , AIRPORT_SERVICE AS AIRPORT_SERVICEalias0 , CITY AS CITYalias0 , FLIGHT AS FLIGHTalias0 WHERE ( AIRPORTalias0.AIRPORT_CODE = " JFK " AND CITYalias0.CITY_CODE = AIRPORT_SERVICEalias0.CITY_CODE AND CITYalias0.CITY_NAME = " MIAMI " AND FLIGHTalias0.FROM_AIRPORT = AIRPORTalias0.AIRPORT_CODE AND FLIGHTalias0.TO_AIRPORT = AIRPORT_SERVICEalias0.AIRPORT_CODE ) AND FLIGHTalias0.AIRLINE_CODE = " DL " ;

what does fare code BH mean
SELECT DISTINCT FARE_BASISalias0.FARE_BASIS_CODE FROM FARE_BASIS AS FARE_BASISalias0 WHERE FARE_BASISalias0.FARE_BASIS_CODE = " BH " ;

what airline is US
SELECT DISTINCT AIRLINEalias0.AIRLINE_CODE FROM AIRLINE AS AIRLINEalias0 WHERE AIRLINEalias0.AIRLINE_CODE = " US " ;

what is 73S
SELECT DISTINCT AIRCRAFTalias0.AIRCRAFT_CODE FROM AIRCRAFT AS AIRCRAFTalias0 WHERE AIRCRAFTalias0.AIRCRAFT_CODE = " 73S " ;

what type of plane is a D9S
SELECT DISTINCT AIRCRAFTalias0.AIRCRAFT_CODE FROM AIRCRAFT AS AIRCRAFTalias0 WHERE AIRCRAFTalias0.AIRCRAFT_CODE = " D9S " ;

show me ground transportation in PHOENIX
SELECT DISTINCT GROUND_SERVICEalias0.TRANSPORT_TYPE FROM CITY AS CITYalias0 , GROUND_SERVICE AS GROUND_SERVICEalias0 WHERE CITYalias0.CITY_NAME = " PHOENIX " AND GROUND_SERVICEalias0.CITY_CODE = CITYalias0.CITY_CODE ;

what is the seating capacity of the aircraft M80
SELECT DISTINCT AIRCRAFTalias0.AIRCRAFT_CODE FROM AIRCRAFT AS AIRCRAFTalias0 WHERE AIRCRAFTalias0.AIRCRAFT_CODE = " M80 " ;

what is the seating capacity of the 757
SELECT DISTINCT AIRCRAFTalias0.AIRCRAFT_CODE FROM AIRCRAFT AS AIRCRAFTalias0 WHERE AIRCRAFTalias0.AIRCRAFT_CODE = " 757 " ;

list LOS ANGELES
SELECT DISTINCT CITYalias0.CITY_CODE FROM CITY AS CITYalias0 WHERE CITYalias0.CITY_NAME = " LOS ANGELES " ;

what airline is DL
SELECT DISTINCT AIRLINEalias0.AIRLINE_CODE FROM AIRLINE AS AIRLINEalias0 WHERE AIRLINEalias0.AIRLINE_CODE = " DL " ;

how many people will a 757 hold
SELECT DISTINCT AIRCRAFTalias0.AIRCRAFT_CODE FROM AIRCRAFT AS AIRCRAFTalias0 WHERE AIRCRAFTalias0.AIRCRAFT_CODE = " 757 " ;

what is seating capacity on the aircraft 73S
SELECT DISTINCT AIRCRAFTalias0.AIRCRAFT_CODE FROM AIRCRAFT AS AIRCRAFTalias0 WHERE AIRCRAFTalias0.AIRCRAFT_CODE = " 73S " ;

list the airlines with flights to or from DENVER
SELECT DISTINCT AIRLINEalias0.AIRLINE_CODE FROM AIRLINE AS AIRLINEalias0 , AIRPORT_SERVICE AS AIRPORT_SERVICEalias0 , CITY AS CITYalias0 , FLIGHT AS FLIGHTalias0 WHERE CITYalias0.CITY_CODE = AIRPORT_SERVICEalias0.CITY_CODE AND CITYalias0.CITY_NAME = " DENVER " AND FLIGHTalias0.AIRLINE_CODE = AIRLINEalias0.AIRLINE_CODE AND FLIGHTalias0.FROM_AIRPORT = AIRPORT_SERVICEalias0.AIRPORT_CODE ;

list ground transportation in BALTIMORE
SELECT DISTINCT GROUND_SERVICEalias0.TRANSPORT_TYPE FROM CITY AS CITYalias0 , GROUND_SERVICE AS GROUND_SERVICEalias0 WHERE CITYalias0.CITY_NAME = " BALTIMORE " AND GROUND_SERVICEalias0.CITY_CODE = CITYalias0.CITY_CODE ;

is there ground transportation available at the INDIANAPOLIS airport
SELECT DISTINCT GROUND_SERVICEalias0.TRANSPORT_TYPE FROM CITY AS CITYalias0 , GROUND_SERVICE AS GROUND_SERVICEalias0 WHERE CITYalias0.CITY_NAME = " INDIANAPOLIS " AND GROUND_SERVICEalias0.CITY_CODE = CITYalias0.CITY_CODE ;

what airline is AS
SELECT DISTINCT AIRLINEalias0.AIRLINE_CODE FROM AIRLINE AS AIRLINEalias0 WHERE AIRLINEalias0.AIRLINE_CODE = " AS " ;

list the AS flights arriving in BURBANK
SELECT DISTINCT FLIGHTalias0.FLIGHT_ID FROM AIRPORT_SERVICE AS AIRPORT_SERVICEalias0 , CITY AS CITYalias0 , FLIGHT AS FLIGHTalias0 WHERE CITYalias0.CITY_CODE = AIRPORT_SERVICEalias0.CITY_CODE AND CITYalias0.CITY_NAME = " BURBANK " AND FLIGHTalias0.AIRLINE_CODE = " AS " AND FLIGHTalias0.TO_AIRPORT = AIRPORT_SERVICEalias0.AIRPORT_CODE ;

what does fare code H mean
SELECT DISTINCT CLASS_OF_SERVICEalias0.BOOKING_CLASS FROM CLASS_OF_SERVICE AS CLASS_OF_SERVICEalias0 WHERE CLASS_OF_SERVICEalias0.BOOKING_CLASS = " H " ;

what cities does NW fly out of
SELECT DISTINCT CITYalias0.CITY_CODE FROM AIRPORT_SERVICE AS AIRPORT_SERVICEalias0 , CITY AS CITYalias0 , FLIGHT AS FLIGHTalias0 WHERE CITYalias0.CITY_CODE = AIRPORT_SERVICEalias0.CITY_CODE AND FLIGHTalias0.AIRLINE_CODE = " NW " AND FLIGHTalias0.FROM_AIRPORT = AIRPORT_SERVICEalias0.AIRPORT_CODE ;

what is the seating capacity of an M80
SELECT DISTINCT AIRCRAFTalias0.AIRCRAFT_CODE FROM AIRCRAFT AS AIRCRAFTalias0 WHERE AIRCRAFTalias0.AIRCRAFT_CODE = " M80 " ;

is there TAXI service at the ONT airport
SELECT DISTINCT GROUND_SERVICEalias0.TRANSPORT_TYPE FROM AIRPORT AS AIRPORTalias0 , GROUND_SERVICE AS GROUND_SERVICEalias0 WHERE AIRPORTalias0.AIRPORT_CODE = " ONT " AND GROUND_SERVICEalias0.AIRPORT_CODE = AIRPORTalias0.AIRPORT_CODE AND GROUND_SERVICEalias0.TRANSPORT_TYPE = " TAXI " ;

ground transportation in LAS VEGAS
SELECT DISTINCT GROUND_SERVICEalias0.TRANSPORT_TYPE FROM CITY AS CITYalias0 , GROUND_SERVICE AS GROUND_SERVICEalias0 WHERE CITYalias0.CITY_NAME = " LAS VEGAS " AND GROUND_SERVICEalias0.CITY_CODE = CITYalias0.CITY_CODE ;

list airports in LOS ANGELES
SELECT DISTINCT AIRPORTalias0.AIRPORT_CODE FROM AIRPORT AS AIRPORTalias0 , AIRPORT_SERVICE AS AIRPORT_SERVICEalias0 , CITY AS CITYalias0 WHERE AIRPORTalias0.AIRPORT_CODE = AIRPORT_SERVICEalias0.AIRPORT_CODE AND CITYalias0.CITY_CODE = AIRPORT_SERVICEalias0.CITY_CODE AND CITYalias0.CITY_NAME = " LOS ANGELES " ;

what is the seating capacity on the aircraft M80
SELECT DISTINCT AIRCRAFTalias0.AIRCRAFT_CODE FROM AIRCRAFT AS AIRCRAFTalias0 WHERE AIRCRAFTalias0.AIRCRAFT_CODE = " M80 " ;

is there ground transportation available at the DENVER airport
SELECT DISTINCT GROUND_SERVICEalias0.TRANSPORT_TYPE FROM CITY AS CITYalias0 , GROUND_SERVICE AS GROUND_SERVICEalias0 WHERE CITYalias0.CITY_NAME = " DENVER " AND GROUND_SERVICEalias0.CITY_CODE = CITYalias0.CITY_CODE ;

what airline is HP
SELECT DISTINCT AIRLINEalias0.AIRLINE_CODE FROM AIRLINE AS AIRLINEalias0 WHERE AIRLINEalias0.AIRLINE_CODE = " HP " ;

is ground transportation available in ST. LOUIS
SELECT DISTINCT GROUND_SERVICEalias0.TRANSPORT_TYPE FROM CITY AS CITYalias0 , GROUND_SERVICE AS GROUND_SERVICEalias0 WHERE CITYalias0.CITY_NAME = " ST. LOUIS " AND GROUND_SERVICEalias0.CITY_CODE = CITYalias0.CITY_CODE ;

what is CVG
SELECT DISTINCT AIRPORTalias0.AIRPORT_CODE FROM AIRPORT AS AIRPORTalias0 WHERE AIRPORTalias0.AIRPORT_CODE = " CVG " ;

list LOS ANGELES
SELECT DISTINCT CITYalias0.CITY_CODE FROM CITY AS CITYalias0 WHERE CITYalias0.CITY_NAME = " LOS ANGELES " ;

what class is fare code Q
SELECT DISTINCT CLASS_OF_SERVICEalias0.BOOKING_CLASS FROM CLASS_OF_SERVICE AS CLASS_OF_SERVICEalias0 WHERE CLASS_OF_SERVICEalias0.BOOKING_CLASS = " Q " ;

what does the restriction ap58 mean
SELECT DISTINCT RESTRICTIONalias0.ADVANCE_PURCHASE , RESTRICTIONalias0.APPLICATION , RESTRICTIONalias0.MAXIMUM_STAY , RESTRICTIONalias0.MINIMUM_STAY , RESTRICTIONalias0.NO_DISCOUNTS , RESTRICTIONalias0.RESTRICTION_CODE , RESTRICTIONalias0.SATURDAY_STAY_REQUIRED , RESTRICTIONalias0.STOPOVERS FROM RESTRICTION AS RESTRICTIONalias0 WHERE RESTRICTIONalias0.RESTRICTION_CODE = " AP/58 " ;

what are the flights from LGA to SAN JOSE on UA
SELECT DISTINCT FLIGHTalias0.FLIGHT_ID FROM AIRPORT AS AIRPORTalias0 , AIRPORT_SERVICE AS AIRPORT_SERVICEalias0 , CITY AS CITYalias0 , FLIGHT AS FLIGHTalias0 WHERE ( AIRPORTalias0.AIRPORT_CODE = " LGA " AND CITYalias0.CITY_CODE = AIRPORT_SERVICEalias0.CITY_CODE AND CITYalias0.CITY_NAME = " SAN JOSE " AND FLIGHTalias0.FROM_AIRPORT = AIRPORTalias0.AIRPORT_CODE AND FLIGHTalias0.TO_AIRPORT = AIRPORT_SERVICEalias0.AIRPORT_CODE ) AND FLIGHTalias0.AIRLINE_CODE = " UA " ;

what is the seating capacity of the type of aircraft M80
SELECT DISTINCT AIRCRAFTalias0.AIRCRAFT_CODE FROM AIRCRAFT AS AIRCRAFTalias0 WHERE AIRCRAFTalias0.AIRCRAFT_CODE = " M80 " ;

i need to RENTAL CAR at TAMPA
SELECT DISTINCT GROUND_SERVICEalias0.TRANSPORT_TYPE FROM AIRPORT AS AIRPORTalias0 , AIRPORT_SERVICE AS AIRPORT_SERVICEalias0 , CITY AS CITYalias0 , GROUND_SERVICE AS GROUND_SERVICEalias0 WHERE AIRPORTalias0.AIRPORT_CODE = AIRPORT_SERVICEalias0.AIRPORT_CODE AND CITYalias0.CITY_CODE = AIRPORT_SERVICEalias0.CITY_CODE AND CITYalias0.CITY_NAME = " TAMPA " AND GROUND_SERVICEalias0.AIRPORT_CODE = AIRPORTalias0.AIRPORT_CODE AND GROUND_SERVICEalias0.TRANSPORT_TYPE = " RENTAL CAR " ;

tell me all the airports in the NEW YORK area
SELECT DISTINCT AIRPORTalias0.AIRPORT_CODE FROM AIRPORT AS AIRPORTalias0 , AIRPORT_SERVICE AS AIRPORT_SERVICEalias0 , CITY AS CITYalias0 WHERE AIRPORTalias0.AIRPORT_CODE = AIRPORT_SERVICEalias0.AIRPORT_CODE AND CITYalias0.CITY_CODE = AIRPORT_SERVICEalias0.CITY_CODE AND CITYalias0.CITY_NAME = " NEW YORK " ;

what airline is AS
SELECT DISTINCT AIRLINEalias0.AIRLINE_CODE FROM AIRLINE AS AIRLINEalias0 WHERE AIRLINEalias0.AIRLINE_CODE = " AS " ;

get flights from MILWAUKEE to DTW

In [42]:
import sqlite3
conn = sqlite3.connect('../data/atis-sqlite.db')
c = conn.cursor()

In [ ]:
c.execute(sql_query)

In [6]:
## Set up voacbulary ##

class Vocab:
    def __init__(self, w2i):
        self.w2i = dict(w2i)
        self.i2w = {i:w for w,i in w2i.items()}

    @classmethod
    def from_corpus(cls, corpus):
        w2i = {}
        for word in corpus:
            w2i.setdefault(word, len(w2i))
        return Vocab(w2i)

    def size(self):
        return len(self.w2i.keys())

def build_vocab(sentences):
    counts = Counter()
    words = {"<UNK>"}
    tag_set = set()
    template_set = set()
    template_to_tagset = {}
    for tokens, tags, template in train:
        template_set.add(template)
        template_to_tagset[template] = set(tags)
        for tag in tags:
            tag_set.add(tag)
        for token in tokens:
            counts[token] += 1

    for word in counts:
        if counts[word] > args.unk_max:
            words.add(word)

    vocab_tags = Vocab.from_corpus(tag_set)
    vocab_words = Vocab.from_corpus(words)
    vocab_templates = Vocab.from_corpus(template_set)

    return vocab_words, vocab_tags, vocab_templates, template_to_tagset

In [7]:
vocab_words, vocab_tags, vocab_templates,template_to_tagset = build_vocab(train)
UNK = vocab_words.w2i["<UNK>"]
NWORDS = vocab_words.size()
NTAGS = vocab_tags.size()
NTEMPLATES = vocab_templates.size()

print("Running with {} templates".format(NTEMPLATES))

Running with 216 templates

In [8]:
## Set up model ##

model = dy.Model()
trainer = dy.SimpleSGDTrainer(model, learning_rate=args.learning_rate)
DIM_WORD = args.dim_word
DIM_HIDDEN_LSTM = args.dim_hidden_lstm
DIM_HIDDEN_MLP = args.dim_hidden_mlp
DIM_HIDDEN_TEMPLATE = args.dim_hidden_template

pEmbedding = model.add_lookup_parameters((NWORDS, DIM_WORD))
if args.word_vectors is not None:
    pretrained = []
    with open(args.word_vectors,'rb') as pickleFile:
        embedding = pickle.load(pickleFile)
        for word_id in range(vocab_words.size()):
            word = vocab_words.i2w[word_id]
            if word in embedding:
                pretrained.append(embedding[word])
            else:
                pretrained.append(pEmbedding.row_as_array(word_id))
    pEmbedding.init_from_array(np.array(pretrained))
if args.mlp:
    pHidden = model.add_parameters((DIM_HIDDEN_MLP, DIM_HIDDEN_LSTM*2))
    pOutput = model.add_parameters((NTAGS, DIM_HIDDEN_MLP))
else:
    pOutput = model.add_parameters((NTAGS, DIM_HIDDEN_LSTM*2))

builders = [
    dy.LSTMBuilder(args.lstm_layers, DIM_WORD, DIM_HIDDEN_LSTM, model),
    dy.LSTMBuilder(args.lstm_layers, DIM_WORD, DIM_HIDDEN_LSTM, model),
]

pHiddenTemplate = model.add_parameters((DIM_HIDDEN_TEMPLATE, DIM_HIDDEN_LSTM*2))
pOutputTemplate = model.add_parameters((NTEMPLATES, DIM_HIDDEN_TEMPLATE))

In [9]:
def build_tagging_graph_bkp(words, tags, template, builders, train=True,k=1):
    dy.renew_cg()

    if train and args.lstm_dropout is not None and args.lstm_dropout > 0:
        for b in builders:
            b.set_dropouts(args.lstm_dropout, args.lstm_dropout)

    f_init, b_init = [b.initial_state() for b in builders]

    wembs = [dy.lookup(pEmbedding, w) for w in words]
    if train: # Add noise in training as a regularizer
        wembs = [dy.noise(we, args.train_noise) for we in wembs]

    fw_states = [x for x in f_init.add_inputs(wembs)]
    bw_states = [x for x in b_init.add_inputs(reversed(wembs))]
    fw = [x.output() for x in fw_states]
    bw = [x.output() for x in bw_states]

    O = dy.parameter(pOutput)
    if args.mlp:
        H = dy.parameter(pHidden)
    errs = []
    pred_tags = []
    sorted_arg_topk = []
    for f, b, t in zip(fw, reversed(bw), tags):
        f_b = dy.concatenate([f,b])
        if args.mlp:
            f_b = dy.tanh(H * f_b)
        r_t = O * f_b
        if train:
            err = dy.pickneglogsoftmax(r_t, t)
            errs.append(err)
        else:
            out = dy.softmax(r_t)
            chosen = np.argmax(out.npvalue())
            pred_tags.append(vocab_tags.i2w[chosen])

    O_template = dy.parameter(pOutputTemplate)
    H_template = dy.parameter(pHiddenTemplate)
    f_bt = dy.concatenate([fw_states[-1].s()[0], bw_states[-1].s()[0]])
    f_bt = dy.tanh(H_template * f_bt)
    r_tt = O_template * f_bt
    pred_template = None
    if train:
        err = dy.pickneglogsoftmax(r_tt, template)
        errs.append(err)
    else:
        out = dy.softmax(r_tt)
        chosen = np.argmax(out.npvalue())        
        pred_template = vocab_templates.i2w[chosen]
        sorted_arg_topk = np.argsort(-out.npvalue())[:k]
        
    return pred_tags, pred_template, errs, sorted_arg_topk

In [22]:
def build_tagging_graph(words, tags, template, builders, train=True,k=1):
    dy.renew_cg()

    if train and args.lstm_dropout is not None and args.lstm_dropout > 0:
        for b in builders:
            b.set_dropouts(args.lstm_dropout, args.lstm_dropout)

    f_init, b_init = [b.initial_state() for b in builders]

    wembs = [dy.lookup(pEmbedding, w) for w in words]
    if train: # Add noise in training as a regularizer
        wembs = [dy.noise(we, args.train_noise) for we in wembs]

    fw_states = [x for x in f_init.add_inputs(wembs)]
    bw_states = [x for x in b_init.add_inputs(reversed(wembs))]
    fw = [x.output() for x in fw_states]
    bw = [x.output() for x in bw_states]

    O = dy.parameter(pOutput)
    if args.mlp:
        H = dy.parameter(pHidden)
    errs = []
    pred_tags = []
    sorted_arg_topk = []
    
    sequences_topk = [(0.0,list())]
    final_topk = []
    for f, b, t in zip(fw, reversed(bw), tags):
        f_b = dy.concatenate([f,b])
        if args.mlp:
            f_b = dy.tanh(H * f_b)
        r_t = O * f_b
        if train:
            err = dy.pickneglogsoftmax(r_t, t)
            errs.append(err)
        else:
            out = dy.log_softmax(r_t)
            chosen = np.argmax(out.npvalue())
            pred_tags.append(vocab_tags.i2w[chosen])
            all_sequences = list()
            for seq in sequences_topk:
                seq_score,seq_list = seq
                _scores = -out.npvalue()
                arg_topk = np.argsort(_scores)[:k]
                score_topk = _scores[arg_topk]
                for i in range(k):
                    _list = list(seq_list)
                    _list.append(vocab_tags.i2w[arg_topk[i]])
                    score = seq_score + score_topk[i]
                    all_sequences.append((score,_list))
            sequences_topk = sorted(all_sequences)[:k]
            

    O_template = dy.parameter(pOutputTemplate)
    H_template = dy.parameter(pHiddenTemplate)
    f_bt = dy.concatenate([fw_states[-1].s()[0], bw_states[-1].s()[0]])
    f_bt = dy.tanh(H_template * f_bt)
    r_tt = O_template * f_bt
    pred_template = None
    if train:
        err = dy.pickneglogsoftmax(r_tt, template)
        errs.append(err)
    else:
        out = dy.log_softmax(r_tt)
        _scores = -out.npvalue()
        chosen = np.argmin(_scores)        
        pred_template = vocab_templates.i2w[chosen]
        sorted_arg_topk = np.argsort(_scores)[:1]
        
        all_sequences_and_templates = []
        for template_id in sorted_arg_topk:
            _score = _scores[template_id]
            _template = vocab_templates.i2w[template_id]

            for seq_score,seq_list in sequences_topk:
                all_sequences_and_templates.append((_score + seq_score, seq_list, _template))
        final_topk = sorted(all_sequences_and_templates)[:k]    
        
        
    return pred_tags, pred_template, errs, final_topk

In [25]:
tagged = 0
loss = 0
best_dev_acc = 0.0
iters_since_best_updated = 0
steps = 0
for iteration in range(args.max_iters):
    random.shuffle(train)
    for tokens, tags, template in train:
        steps += 1

        # Convert to indices
        word_ids = [vocab_words.w2i.get(word, UNK) for word in tokens]
        tag_ids = [vocab_tags.w2i[tag] for tag in tags]
        template_id = vocab_templates.w2i[template]

        # Decode and update
        _, _, errs,_ = build_tagging_graph(word_ids, tag_ids, template_id, builders)
        sum_errs = dy.esum(errs)
        loss += sum_errs.scalar_value()
        tagged += len(tag_ids)
        sum_errs.backward()
        trainer.update()

        # Log status
        if steps % args.log_freq == 0:
            trainer.status()
            print("TrainLoss {}-{}: {}".format(iteration, steps, loss / tagged))
            loss = 0
            tagged = 0
            sys.stdout.flush()
        if steps % args.eval_freq == 0:
            acc = run_eval(dev, builders, iteration, steps)
            if best_dev_acc < acc:
                best_dev_acc = acc
                iters_since_best_updated = 0
                print("New best Acc!", acc)
            sys.stdout.flush()
    iters_since_best_updated += 1
    if args.max_bad_iters > 0 and iters_since_best_updated > args.max_bad_iters:
        print("Stopping at iter {} as there have been {} iters without improvement".format(iteration, args.max_bad_iters))
        break

Stopping at iter 1 as there have been 1 iters without improvement

In [26]:
def run_eval(data, builders, iteration, step,k):
    if len(data) == 0:
        print("No data for eval")
        return -1
    good = 0.0
    total = 0.0
    complete_good = 0.0
    templates_good = 0.0
    oracle = 0.0
    tag_set_wrong = 0.0
    for tokens, tags, template in data:
        word_ids = [vocab_words.w2i.get(word, UNK) for word in tokens]
        tag_ids = [0 for tag in tags]
        pred_tags, pred_template, _ , final_topk = build_tagging_graph(word_ids, tag_ids, 0, builders, False,k=k)
        gold_tags = tags
        perfect = True
        
        for score, _tags, _template in final_topk:
            if template_to_tagset[_template] == set(_tags):
                pred_tags = _tags
                pred_template = _template
                break;
        
        for gold, pred in zip(gold_tags, pred_tags):
            total += 1
            if gold == pred: 
                good += 1
            else:
                perfect = False
                
        
#         for template_id in pred_arg_topk:
#             pred_template = vocab_templates.i2w[template_id]
#             if template_to_tagset[pred_template] == set(pred_tags):
#                 break;
    
            
        if template_to_tagset[pred_template] != set(pred_tags):
            tag_set_wrong += 1
        
        if pred_template == template:
            templates_good += 1
            if perfect:
                complete_good += 1
        if template in vocab_templates.w2i:
            oracle += 1
    tok_acc = good / total
    
    tagset_acc = tag_set_wrong/ len(data)
    complete_acc = complete_good / len(data)
    template_acc = templates_good / len(data)
    oracle_acc = oracle / len(data)
    print("Eval {}-{} Acc: {:>5} Tmpl: {:<5} Tot: {:>5} Orcl: {:>5} Tag: {:>5}".format(iteration, step, tok_acc, template_acc, complete_acc, oracle_acc, tagset_acc))
    return complete_acc

In [27]:
run_eval(test[:60], builders, "End", "test",1)

Eval End-test Acc: 0.9883381924198251 Tmpl: 0.8333333333333334 Tot: 0.7833333333333333 Orcl:   1.0 Tag:   0.1

0.7833333333333333

In [28]:
for k in range(10):
    run_eval(test, builders, "End", "test",k)

Eval End-test Acc: 0.989159465828751 Tmpl: 0.8481675392670157 Tot: 0.787085514834206 Orcl: 0.9982547993019197 Tag: 0.12390924956369982
Eval End-test Acc: 0.989159465828751 Tmpl: 0.8481675392670157 Tot: 0.787085514834206 Orcl: 0.9982547993019197 Tag: 0.12390924956369982
Eval End-test Acc: 0.991044776119403 Tmpl: 0.8481675392670157 Tot: 0.8080279232111692 Orcl: 0.9982547993019197 Tag: 0.09075043630017451
Eval End-test Acc: 0.9912018853102906 Tmpl: 0.8481675392670157 Tot: 0.8150087260034904 Orcl: 0.9982547993019197 Tag: 0.06806282722513089
Eval End-test Acc: 0.991516103692066 Tmpl: 0.8481675392670157 Tot: 0.8167539267015707 Orcl: 0.9982547993019197 Tag: 0.05410122164048865
Eval End-test Acc: 0.9913589945011784 Tmpl: 0.8481675392670157 Tot: 0.8167539267015707 Orcl: 0.9982547993019197 Tag: 0.05235602094240838
Eval End-test Acc: 0.9913589945011784 Tmpl: 0.8481675392670157 Tot: 0.8167539267015707 Orcl: 0.9982547993019197 Tag: 0.05235602094240838
Eval End-test Acc: 0.991516103692066 Tmpl: 0.8481675392670157 Tot: 0.8167539267015707 Orcl: 0.9982547993019197 Tag: 0.0506108202443281
Eval End-test Acc: 0.9913589945011784 Tmpl: 0.8481675392670157 Tot: 0.8167539267015707 Orcl: 0.9982547993019197 Tag: 0.04886561954624782
Eval End-test Acc: 0.9913589945011784 Tmpl: 0.8481675392670157 Tot: 0.8167539267015707 Orcl: 0.9982547993019197 Tag: 0.04886561954624782